/*******************************************************************************
 * Copyright (c) 2015-2016 IncQuery Labs Ltd. and Ericsson AB
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Akos Horvath, Abel Hegedus, Zoltan Ujhelyi, Daniel Segesdi, Tamas Borbas, Robert Doczi, Peter Lunk - initial API and implementation
 *******************************************************************************/
/******************************************************************************
 * 
 * M A I N
 * 
 * NAME: main
 * 
 * Generated by EMDW-MC
 * 
 ******************************************************************************/


#include "PhoneX/ComponentLibrary/PhoneX/PhoneX_def.hh"

int main(int , char **) {
	::PhoneX::ComponentLibrary::PhoneX::ImplementationPkg::testfunctions::runAll();

	auto comp = ::PhoneX::ComponentLibrary::PhoneX::PhoneX::get_instance();
	for (int i = 0; i < 1000; ++i) {
		comp->process();
	}
}
