/******************************************************************************
 * 
 * M A I N
 * 
 * NAME: main
 * 
 * Generated by EMDW-MC
 * 
 ******************************************************************************/


#include "PhoneX/ComponentLibrary/PhoneX/PhoneX_def.hh"

int main(int , char **) {
	::PhoneX::ComponentLibrary::PhoneX::ImplementationPkg::testfunctions::runAll();

	auto comp = ::PhoneX::ComponentLibrary::PhoneX::PhoneX::get_instance();
	for (int i = 0; i < 1000; ++i) {
		comp->process();
	}
}
